import {
  certifications,
  experienceTimeline,
  recruiterProfile,
  terminalSkillSections,
} from './data/recruiterProfile';

export const TERMINAL_COMMANDS = {
  whoami: [
    { text: recruiterProfile.name.toLowerCase(), color: "accent" },
    { text: recruiterProfile.terminalHeadline, color: "secondary" },
    { text: recruiterProfile.shortIntro, color: "secondary" },
    { text: `location: ${recruiterProfile.location.terminal} — open to relocation`, color: "secondary" },
    { text: "" },
    { text: "type 'help' for available commands", color: "muted" },
  ],
  help: [
    { text: "available commands:", color: "accent" },
    { text: "" },
    { text: " whoami — identify the operator", color: "secondary" },
    { text: " cat experience.log — full career history", color: "secondary" },
    { text: " cat skills.txt — competency map", color: "secondary" },
    { text: " ls ./projects — list projects", color: "secondary" },
    { text: " open venderscope — launch risk intelligence tool", color: "secondary" },
    { text: " ssh contact@szh.dev — initiate contact sequence", color: "secondary" },
    { text: " open about.txt — operator profile", color: "secondary" },
    { text: " ps / htop — running process snapshot", color: "secondary" },
    { text: " nmap szh_os — port scan of the live stack", color: "secondary" },
    { text: " traceroute szh.dev — hop path to contact", color: "secondary" },
    { text: " neofetch — system info banner", color: "secondary" },
    { text: " man zarak — operator manual page", color: "secondary" },
    { text: " ascii — render the szh_os banner", color: "secondary" },
    { text: " fortune — one line from the operator log", color: "secondary" },
    { text: " uptime — real session uptime, not a fake counter", color: "secondary" },
    { text: " history — this session's command log", color: "secondary" },
    { text: " matrix — you know what this does", color: "secondary" },
    { text: " clear — clear terminal", color: "secondary" },
    { text: "" },
    { text: " (some operators run 'sudo -l' out of habit)", color: "muted" },
    { text: " (this list is not exhaustive — some doors aren't labeled)", color: "muted" },
  ],
  "cat experience.log": [
    { text: "reading /var/log/career_events.log...", color: "muted" },
    { text: "" },
    ...experienceTimeline.flatMap((entry) => [
      { text: "───────────────────────────────────────────", color: "border" as const },
      { text: entry.date, color: entry.status === 'ACTIVE' ? "warn" : entry.status === 'IN_PROGRESS' ? "warn" : "muted" as const },
      { text: `${entry.company} — ${entry.role}`, color: "accent" as const },
      ...(entry.terminalSubtitle ? [{ text: entry.terminalSubtitle, color: "secondary" as const }] : []),
      { text: "", color: "secondary" as const },
      ...entry.terminalLines,
      { text: "", color: "secondary" as const },
      { text: ` status: ${entry.status}`, color: entry.status === 'ACTIVE' ? "green" : entry.status === 'IN_PROGRESS' ? "warn" : "muted" as const },
    ]),
    { text: "───────────────────────────────────────────", color: "border" },
  ],
  "cat skills.txt": [
    { text: "reading /etc/operator/skills.txt...", color: "muted" },
    { text: "" },
    ...terminalSkillSections.flatMap((section) =>
      section.lines.map((line, index) => ({
        text: `${index === 0 ? `${section.label} ` : ' '}${line}`,
        color: "secondary" as const,
      })),
    ),
    { text: "" },
    { text: "CERTIFICATIONS", color: "accent" },
    ...certifications
      .slice()
      .reverse()
      .map((certification) => ({ text: ` ${certification.terminalLabel}`, color: "secondary" as const })),
  ],
  "ls ./projects": [
    { text: "listing /home/zarak/projects/...", color: "muted" },
    { text: "" },
    { text: "drwxr-xr-x venderscope/", color: "accent" },
    { text: " continuous vendor risk intelligence platform", color: "secondary" },
    { text: " stack: python · react · hibp · nvd · shodan · companies house", color: "muted" },
    { text: " live at: venderscope.vercel.app", color: "secondary" },
    { text: "" },
    { text: "drwxr-xr-x speedyrentals/", color: "accent" },
    { text: " secure full-stack car rental web application", color: "secondary" },
    { text: " stack: firebase · owasp-aligned · role-based access control", color: "muted" },
    { text: " via: github.com/syed-hassan7/SpeedyRentals", color: "secondary" },
    { text: "" },
    { text: "drwxr-xr-x claude-harness/", color: "accent" },
    { text: " portable skill-and-rules pack for AI coding agents", color: "secondary" },
    { text: " stack: shell · markdown rules · yaml skill contract", color: "muted" },
    { text: " via: github.com/syed-hassan7/claude-harness", color: "secondary" },
    { text: "" },
    { text: "drwxr-xr-x red-team-desk/", color: "accent" },
    { text: " static security + GRC readiness tool (Sentinel Red)", color: "secondary" },
    { text: " stack: python · static analysis · SARIF export", color: "muted" },
    { text: " via: github.com/syed-hassan7/red-team-desk", color: "secondary" },
    { text: "" },
    { text: "drwxr-xr-x maternify/", color: "accent" },
    { text: " multilingual safety-gated AI maternal advocacy platform", color: "secondary" },
    { text: " stack: next.js · glm-5.1 · gemini · rag over nhs docs", color: "muted" },
    { text: " built in 24h at vibehack london 2026 — 5th, health impact", color: "secondary" },
    { text: " live at: maternify-theta.vercel.app", color: "secondary" },
    { text: "" },
    { text: "drwxr-xr-x presales-n8n/", color: "accent" },
    { text: " agentic tender/RFP response suite (n8n + Claude)", color: "secondary" },
    { text: " stack: n8n · claude · pdf ingest · slack alerts", color: "muted" },
    { text: " result: bid lifecycle 57% faster", color: "secondary" },
    { text: "" },
    { text: "drwxr-xr-x szh_os/", color: "accent" },
    { text: " you are here", color: "muted" },
    { text: "" },
    { text: " type 'open venderscope' to launch the live tool", color: "muted" },
  ],
  "open venderscope": [
    { text: "launching venderscope.browser...", color: "muted" },
    { text: "resolving venderscope.vercel.app...", color: "muted" },
    { text: "connection established.", color: "green" },
    { text: "opening window.", color: "muted" },
    { text: "", action: "OPEN_WINDOW", target: "venderscope.browser" },
  ],
  "ssh contact@szh.dev": [
    { text: "initiating contact sequence...", color: "muted" },
    { text: "establishing secure channel...", color: "green" },
    { text: "opening contact session.", color: "muted" },
    { text: "", action: "OPEN_WINDOW", target: "contact.ssh" },
  ],
  "open about.txt": [
    { text: "opening /home/zarak/about.txt...", color: "muted" },
    { text: "", action: "OPEN_WINDOW", target: "about.txt" },
  ],
  clear: [
    { text: "", action: "CLEAR" },
  ],
  "sudo -l": [
    { text: "Matching Defaults entries for zarak on szh_os:", color: "muted" },
    { text: "" },
    { text: "User zarak may run the following commands on szh_os:", color: "accent" },
    { text: " (ALL) sudo hire-zarak", color: "secondary" },
    { text: " (ALL) cat classified.txt", color: "secondary" },
    { text: " (ALL) sudo rm -rf /", color: "secondary" },
  ],
  "sudo hire-zarak": [
    { text: "[sudo] password for recruiter: ", color: "muted" },
    { text: "authenticating against candidate_pool...", color: "muted" },
    { text: "permission granted.", color: "green" },
    { text: "provisioning offer letter...", color: "muted" },
    { text: "role: full-time. compensation: negotiable. start date: yesterday.", color: "secondary" },
    { text: "", color: "secondary" },
    { text: "he already knows why you're here. run 'ssh contact@szh.dev' when ready.", color: "muted" },
  ],
  "cat classified.txt": [
    { text: "reading /root/classified.txt...", color: "muted" },
    { text: "" },
    { text: "SUBJECT: ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓", color: "danger" },
    { text: "CLEARANCE: ▓▓▓▓▓▓▓▓▓▓ [REDACTED]", color: "danger" },
    { text: "NOTES: this operator does not leave ▓▓▓▓▓▓▓▓ lying around.", color: "danger" },
    { text: "" },
    { text: "ACCESS DENIED.", color: "danger" },
    { text: "attempt logged. nice try though.", color: "muted" },
  ],
  "sudo rm -rf /": [
    { text: "rm: cannot remove '/': blocked by change-control policy", color: "danger" },
    { text: "initiating rollback simulation...", color: "muted" },
    { text: "", action: "GLITCH" },
    { text: "...deletion aborted. integrity restored.", color: "green" },
    { text: "this is the GRC talking. try 'help' instead.", color: "muted" },
  ],
  ps: [
    { text: "PID   USER    CPU  MEM   COMMAND", color: "accent" },
    { text: "1     zarak   0.1  0.4   init(szh_os)", color: "secondary" },
    { text: "214   zarak   2.3  1.8   gemini-worker", color: "secondary" },
    { text: "215   zarak   0.4  0.6   redis-conn (upstash)", color: "secondary" },
    { text: "233   zarak   0.2  0.3   grc-daemon", color: "secondary" },
    { text: "241   zarak   0.1  0.2   rate-limiter", color: "secondary" },
    { text: "252   zarak   0.0  0.1   sudo-hire-zarak (sleeping)", color: "muted" },
    { text: "300   zarak   0.6  0.9   terminal.app", color: "accent" },
    { text: "", color: "secondary" },
    { text: "6 processes, 1 waiting on you", color: "muted" },
  ],
  htop: [
    { text: "PID   USER    CPU  MEM   COMMAND", color: "accent" },
    { text: "1     zarak   0.1  0.4   init(szh_os)", color: "secondary" },
    { text: "214   zarak   2.3  1.8   gemini-worker", color: "secondary" },
    { text: "215   zarak   0.4  0.6   redis-conn (upstash)", color: "secondary" },
    { text: "233   zarak   0.2  0.3   grc-daemon", color: "secondary" },
    { text: "241   zarak   0.1  0.2   rate-limiter", color: "secondary" },
    { text: "252   zarak   0.0  0.1   sudo-hire-zarak (sleeping)", color: "muted" },
    { text: "300   zarak   0.6  0.9   terminal.app", color: "accent" },
    { text: "", color: "secondary" },
    { text: "6 processes, 1 waiting on you", color: "muted" },
  ],
  "nmap szh_os": [
    { text: "starting nmap 7.94 ( https://nmap.org )", color: "muted" },
    { text: "scan report for szh_os (production)", color: "muted" },
    { text: "" },
    { text: "PORT      STATE    SERVICE   NOTES", color: "accent" },
    { text: "443/tcp   open     https     vercel edge network + tls termination", color: "secondary" },
    { text: "443/tcp   open     api/ask   edge function, gemini-backed, rate-limited", color: "secondary" },
    { text: "443/tcp   open     api/notes edge function, upstash-redis backed", color: "secondary" },
    { text: "6379/tcp  filtered redis     upstash — edge-only, not directly reachable", color: "secondary" },
    { text: "22/tcp    closed   ssh       use 'ssh contact@szh.dev' instead", color: "secondary" },
    { text: "" },
    { text: "nmap done: 1 host scanned, 0 vulnerabilities, 1 hireable.", color: "green" },
  ],
  "nmap localhost": [
    { text: "starting nmap 7.94 ( https://nmap.org )", color: "muted" },
    { text: "scan report for szh_os (production)", color: "muted" },
    { text: "" },
    { text: "PORT      STATE    SERVICE   NOTES", color: "accent" },
    { text: "443/tcp   open     https     vercel edge network + tls termination", color: "secondary" },
    { text: "443/tcp   open     api/ask   edge function, gemini-backed, rate-limited", color: "secondary" },
    { text: "443/tcp   open     api/notes edge function, upstash-redis backed", color: "secondary" },
    { text: "6379/tcp  filtered redis     upstash — edge-only, not directly reachable", color: "secondary" },
    { text: "22/tcp    closed   ssh       use 'ssh contact@szh.dev' instead", color: "secondary" },
    { text: "" },
    { text: "nmap done: 1 host scanned, 0 vulnerabilities, 1 hireable.", color: "green" },
  ],
  "traceroute szh.dev": [
    { text: "traceroute to szh.dev, 8 hops max", color: "muted" },
    { text: " 1  you.local                0.4 ms", color: "secondary" },
    { text: " 2  isp-edge.net             6.1 ms", color: "secondary" },
    { text: " 3  tier1-backbone.net      14.8 ms", color: "secondary" },
    { text: " 4  vercel-edge.iad1        21.3 ms", color: "secondary" },
    { text: " 5  vercel-edge.lhr1        24.7 ms", color: "secondary" },
    { text: " 6  szh_os (production)     25.0 ms", color: "accent" },
    { text: "" },
    { text: "route resolved. operator reachable — try 'ssh contact@szh.dev'.", color: "green" },
  ],
  neofetch: [
    { text: `${recruiterProfile.name.toLowerCase()}@szh_os`, color: "accent" },
    { text: "-----------------", color: "secondary" },
    { text: "os: szh_os v2 (portfolio build)", color: "secondary" },
    { text: "host: syed zarak hassan — grc / security / builder", color: "secondary" },
    { text: "shell: terminal.app", color: "secondary" },
    { text: "stack: react 19 · vite · tailwind v4 · motion · three.js", color: "secondary" },
    { text: "hosting: vercel edge network", color: "secondary" },
    { text: "storage: upstash redis (rate-limited edge functions)", color: "secondary" },
    { text: "theme: cyber-noir, jetbrains mono", color: "secondary" },
    { text: "uptime: this page load only — run 'uptime' for the real number", color: "muted" },
  ],
  "man zarak": [
    { text: "ZARAK(1)                    operator manual                    ZARAK(1)", color: "accent" },
    { text: "" },
    { text: "NAME", color: "accent" },
    { text: "     zarak — grc / security operator, full-stack builder", color: "secondary" },
    { text: "" },
    { text: "SYNOPSIS", color: "accent" },
    { text: "     zarak [--hire] [--contact] [--coffee-chat]", color: "secondary" },
    { text: "" },
    { text: "DESCRIPTION", color: "accent" },
    { text: "     ships security tooling that survives an audit, and", color: "secondary" },
    { text: "     product surfaces that survive real users.", color: "secondary" },
    { text: "     no invented metrics. no hallucinated case studies.", color: "secondary" },
    { text: "" },
    { text: "EXIT STATUS", color: "accent" },
    { text: "     0  role filled", color: "secondary" },
    { text: "     1  still open to relocation", color: "secondary" },
    { text: "" },
    { text: "SEE ALSO", color: "accent" },
    { text: "     whoami(1), cat-experience.log(5), sudo-hire-zarak(8)", color: "secondary" },
  ],
  ascii: [
    { text: " ███████╗███████╗██╗  ██╗    ██████╗ ███████╗", color: "accent" },
    { text: " ██╔════╝╚══███╔╝██║  ██║   ██╔═══██╗██╔════╝", color: "accent" },
    { text: " ███████╗  ███╔╝ ███████║   ██║   ██║███████╗", color: "accent" },
    { text: " ╚════██║ ███╔╝  ██╔══██║   ██║   ██║╚════██║", color: "accent" },
    { text: " ███████║███████╗██║  ██║   ╚██████╔╝███████║", color: "accent" },
    { text: " ╚══════╝╚══════╝╚═╝  ╚═╝    ╚═════╝ ╚══════╝", color: "accent" },
    { text: "" },
    { text: " grc. security. builder.", color: "secondary" },
  ],
  fortune: [
    { text: "", action: "FORTUNE" },
  ],
  uptime: [
    { text: "reading /proc/uptime...", color: "muted" },
    { text: "", action: "UPTIME" },
  ],
  "cat /proc/uptime": [
    { text: "reading /proc/uptime...", color: "muted" },
    { text: "", action: "UPTIME" },
  ],
  history: [
    { text: "", action: "HISTORY" },
  ],
  matrix: [
    { text: "wake up, operator...", color: "accent" },
    { text: "", action: "MATRIX" },
  ],
  "cat .env": [
    { text: "cat: .env: permission denied", color: "danger" },
    { text: "nice try. no secrets stored client-side — this is a static build.", color: "muted" },
  ],
  "ls -la": [
    { text: "total 0", color: "muted" },
    { text: "drwxr-xr-x  you-are-here", color: "secondary" },
    { text: "-rw-------  .env                 permission denied", color: "danger" },
    { text: "" },
    { text: "no secrets stored client-side. anything sensitive lives server-side, in env vars vercel manages.", color: "muted" },
  ],
  override: [
    { text: "escalating privileges...", color: "muted" },
    { text: "bypassing standard auth flow...", color: "warn" },
    { text: "", action: "OVERRIDE" },
    { text: "session flagged. operator notified. welcome anyway.", color: "muted" },
  ],
  "decrypt classified.txt": [
    { text: "attempting decrypt on /root/classified.txt...", color: "muted" },
    { text: "", action: "SCRAMBLE_REVEAL" },
    { text: "SUBJECT: syed zarak hassan", color: "accent", scramble: true },
    { text: "CLEARANCE: full — nothing sensitive was ever stored here", color: "secondary", scramble: true },
    { text: "NOTES: the redaction in classified.txt was cosmetic, not cryptographic", color: "secondary", scramble: true },
    { text: "" },
    { text: "decryption complete.", color: "green" },
  ],
};

export const FORTUNE_LINES: string[] = [
  "evidence beats opinion, every time.",
  "a control without a test is a hope.",
  "ship the boring fix before the clever one.",
  "if it is not logged, it did not happen.",
  "trust is a control, not a policy.",
  "the fastest audit is the one you already did.",
  "assume breach. verify anyway.",
  "a good runbook outlives its author.",
  "security theater fails the same way it looks.",
  "a vendor's risk is your risk on a longer clock.",
  "the best incident response was the boring prevention.",
  "recruiters skim. systems don't lie. build for both.",
];

export const TERM_COLORS = {
  accent: "text-os-accent",
  secondary: "text-os-text-sec",
  muted: "text-os-text-sec/90",
  warn: "text-os-warn",
  green: "text-os-accent", // Using accent for green as per instructions or close enough
  danger: "text-os-danger",
  border: "text-os-border",
};
