export const TERMINAL_COMMANDS = {
  whoami: [
    { text: "syed zarak hassan", color: "accent" },
    { text: "compliance analyst @ thrive learning // msc cybersecurity — ntu 2026", color: "secondary" },
    { text: "building tools that catch what audits miss", color: "secondary" },
    { text: "location: nottingham, uk — open to relocation", color: "secondary" },
    { text: "" },
    { text: "type 'help' for available commands", color: "muted" },
  ],
  help: [
    { text: "available commands:", color: "accent" },
    { text: "" },
    { text: " whoami — identify the operator", color: "secondary" },
    { text: " cat experience.log — full career history", color: "secondary" },
    { text: " cat skills.txt — competency map", color: "secondary" },
    { text: " ls ./projects — list projects", color: "secondary" },
    { text: " open venderscope — launch risk intelligence tool", color: "secondary" },
    { text: " ssh contact@szh.dev — initiate contact sequence", color: "secondary" },
    { text: " open about.txt — operator profile", color: "secondary" },
    { text: " clear — clear terminal", color: "secondary" },
  ],
  "cat experience.log": [
    { text: "reading /var/log/career_events.log...", color: "muted" },
    { text: "" },
    { text: "───────────────────────────────────────────", color: "border" },
    { text: "[2025-09 → present]", color: "warn" },
    { text: "THRIVE LEARNING — Compliance Analyst", color: "accent" },
    { text: " Fixed-term contract · Nottingham, UK", color: "secondary" },
    { text: "" },
    { text: " → MDM migration to Kandji: 250 endpoints, 0 downtime", color: "secondary" },
    { text: " result: IT support tickets reduced by 40%", color: "muted" },
    { text: " → Built company-wide DPA tracking system", color: "secondary" },
    { text: " result: time-to-approval reduced by 70%", color: "muted" },
    { text: " → ISO 9001 Stage 1 audit: passed", color: "secondary" },
    { text: " authored 6 end-to-end business process flows", color: "muted" },
    { text: " → 50+ vendor audits managed in Vanta", color: "secondary" },
    { text: " → Delivered RFI response that closed high-value prospect", color: "secondary" },
    { text: " → 75+ application ownership records maintained in Cakewalk", color: "secondary" },
    { text: "" },
    { text: " status: ACTIVE", color: "green" },
    { text: "───────────────────────────────────────────", color: "border" },
    { text: "[2021-09 → 2024-08]", color: "muted" },
    { text: "NEXIQUE DESIGN LABS — Lead Project Manager", color: "accent" },
    { text: " Lahore, Pakistan", color: "secondary" },
    { text: "" },
    { text: " → 15+ client projects delivered end-to-end", color: "secondary" },
    { text: " → $8,500+ revenue generated, ~100% client satisfaction", color: "secondary" },
    { text: " → Led and mentored a 5-person team", color: "secondary" },
    { text: " → Built standardised onboarding workflows from scratch", color: "secondary" },
    { text: "" },
    { text: " status: CLOSED", color: "muted" },
    { text: "───────────────────────────────────────────", color: "border" },
    { text: "[2025-01 → 2026-12]", color: "warn" },
    { text: "MSc CYBER SECURITY — Nottingham Trent University", color: "accent" },
    { text: "" },
    { text: " → Dissertation: do diagrams improve auditor comprehension?", color: "secondary" },
    { text: " (spoiler: yes — measurably)", color: "muted" },
    { text: " → Modules: Network Security · Digital Forensics", color: "secondary" },
    { text: " Secure Software Development · Ethical Hacking", color: "secondary" },
    { text: "" },
    { text: " status: IN_PROGRESS", color: "warn" },
    { text: "───────────────────────────────────────────", color: "border" },
  ],
  "cat skills.txt": [
    { text: "reading /etc/operator/skills.txt...", color: "muted" },
    { text: "" },
    { text: "FRAMEWORKS iso 27001 · iso 9001 · cyber essentials · nist · cia triad", color: "secondary" },
    { text: "GRC risk register · vendor risk · gdpr · dpa tracking", color: "secondary" },
    { text: " access control · auditing · data privacy · bcp", color: "secondary" },
    { text: "SEC OPS iam · endpoint security · incident response · dlp", color: "secondary" },
    { text: " vulnerability management · security awareness training", color: "secondary" },
    { text: "SIEM splunk · chronicle · suricata · wireshark · virustotal", color: "secondary" },
    { text: " bitdefender gravityzone · tcpdump", color: "secondary" },
    { text: "MDM / IT kandji · pulseway · vanta · cakewalk · jira", color: "secondary" },
    { text: "DEV python · mysql · react · linux (mint + ubuntu) · macos", color: "secondary" },
    { text: "SOFT project management · stakeholder engagement", color: "secondary" },
    { text: " pre-sales support · client onboarding · strategic planning", color: "secondary" },
    { text: "" },
    { text: "CERTIFICATIONS", color: "accent" },
    { text: " google professional cybersecurity certificate (2024)", color: "secondary" },
    { text: " soc analyst learning path — letsdefend + hackthebox (2024)", color: "secondary" },
  ],
  "ls ./projects": [
    { text: "listing /home/zarak/projects/...", color: "muted" },
    { text: "" },
    { text: "drwxr-xr-x venderscope/", color: "accent" },
    { text: " continuous vendor risk intelligence platform", color: "secondary" },
    { text: " stack: python · react · hibp · nvd · shodan · companies house", color: "muted" },
    { text: " live at: venderscope.vercel.app", color: "secondary" },
    { text: "" },
    { text: "drwxr-xr-x speedyrentals/", color: "accent" },
    { text: " secure full-stack car rental web application", color: "secondary" },
    { text: " stack: firebase · owasp-aligned · role-based access control", color: "muted" },
    { text: " via: github.com/darkyzowo/SpeedyRentals", color: "secondary" },
    { text: "" },
    { text: "drwxr-xr-x szh_os/", color: "accent" },
    { text: " you are here", color: "muted" },
    { text: "" },
    { text: " type 'open venderscope' to launch the live tool", color: "muted" },
  ],
  "open venderscope": [
    { text: "launching venderscope.browser...", color: "muted" },
    { text: "resolving venderscope.vercel.app...", color: "muted" },
    { text: "connection established.", color: "green" },
    { text: "opening window.", color: "muted" },
    { text: "", action: "OPEN_WINDOW", target: "venderscope.browser" },
  ],
  "ssh contact@szh.dev": [
    { text: "initiating contact sequence...", color: "muted" },
    { text: "establishing secure channel...", color: "green" },
    { text: "opening contact session.", color: "muted" },
    { text: "", action: "OPEN_WINDOW", target: "contact.ssh" },
  ],
  "open about.txt": [
    { text: "opening /home/zarak/about.txt...", color: "muted" },
    { text: "", action: "OPEN_WINDOW", target: "about.txt" },
  ],
  clear: [
    { text: "", action: "CLEAR" },
  ],
};

export const TERM_COLORS = {
  accent: "text-os-accent",
  secondary: "text-os-text-sec",
  muted: "text-os-text-sec/60",
  warn: "text-os-warn",
  green: "text-os-accent", // Using accent for green as per instructions or close enough
  danger: "text-os-danger",
  border: "text-os-border",
};
